name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        components: rustfmt, clippy

    - name: Build project
      run: cargo build --release

    - name: Run tests
      run: cargo test --verbose

    - name: Lint with Clippy
      run: cargo clippy -- -D warnings

    - name: Format code
      run: cargo fmt -- --check
